### ISSUE TITLE
Your release and documentation are not matching

### ISSUE THREAD

**Issue by optiwariindia** [paytm/paytm-pg-php-sdk#5]
I am facing issue while initalizing. I am not able to find what is client id. I randomly given a client id while initialization but is not working as expected.

**Comment by chandrabhan11** [comment]
yes uou erh

**Comment by aarushisoni** [comment]
Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.

**Comment by rahul2bisht** [comment]
Hi
The issue is fixed already and we had updated the repository with changes already in previous commit.

**Comment by optiwariindia** [comment]
Rahul bhai... issue jab fix hua to bata bhi to dena chahiye... jisne issue raise kia tha usko pata hi nahi...
